name: datahub_postgres
description: A sample command-line application.
version: 0.1.0-dev.1
homepage: https://datahubproject.net
repository: https://github.com/christian-thiele/datahub_postgres

environment:
  sdk: ^3.1.0

dependencies:
  boost: ^1.8.9
  buffer: ^1.2.2
  datahub: ^0.17.0-dev.52
  postgres: ^2.6.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  datahub_codegen: ^0.17.0-dev.15
  build_runner: ^2.4.6
